import {test, expect} from '@playwright/test';

test('2FA entries copy on demand, edit and survive encrypted reload', async ({page, context}) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.clock.setFixedTime(new Date(1111111109000));
  await page.goto('/');
  const password = 'daily-vault-passphrase';
  await expect(page.locator('.auth-box')).toBeVisible();
  if (await page.getByLabel('新主密码', {exact: true}).count()) {
    await page.getByLabel('新主密码', {exact: true}).fill(password);
    await page.getByLabel('重复主密码', {exact: true}).fill(password);
    await page.getByRole('button', {name: '创建保险库'}).click();
  } else {
    await page.getByLabel('主密码', {exact: true}).fill(password);
    await page.getByRole('button', {name: '解锁', exact: true}).click();
  }
  await expect(page.getByRole('list', {name: '条目河流'})).toBeVisible();
  const secret = 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ';
  const body = `GitHub 2FA\ntotp: ${secret}`;
  await page.keyboard.press('o');
  const editor = page.getByRole('textbox', {name: '编辑条目'});
  await editor.fill(body);
  await editor.press('Escape');
  await expect(page.locator('.sync-status')).toHaveAttribute('data-state', 'clean');
  const entry = page.getByRole('listitem').filter({hasText: 'GitHub 2FA'});
  const copy = entry.getByRole('button', {name: '复制验证码', exact: true});
  await expect(copy).toHaveText('复制验证码');
  await expect(entry.locator('.entry-text')).toHaveText(body);
  await expect(entry.locator('.totp-countdown')).toHaveCount(0);
  await copy.click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('081804');
  await expect(editor).toHaveCount(0);
  await page.keyboard.press('o');
  await editor.fill('尚未提交的草稿');
  await page.clock.setFixedTime(new Date(1111111110000));
  await expect(copy).toHaveText('复制验证码');
  await expect(entry.locator('.totp-countdown')).toHaveCount(0);
  await expect(editor).toHaveValue('尚未提交的草稿');
  await expect(editor).toBeFocused();
  await editor.fill('');
  await editor.press('Escape');
  await copy.click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('050471');
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('denied'); }; });
  await copy.click();
  await expect(copy).toHaveText('复制失败，请重试');
  await expect(copy).toBeEnabled();
  const response = await page.request.get('/api/snapshot');
  expect(response.ok()).toBe(true);
  const snapshot = await response.text();
  expect(snapshot).not.toContain(secret);
  expect(snapshot).not.toContain('GitHub 2FA');
  await page.reload();
  await page.getByLabel('主密码', {exact: true}).fill(password);
  await page.getByRole('button', {name: '解锁', exact: true}).click();
  await expect(copy).toHaveText('复制验证码');
  await entry.locator('.entry-text').click();
  await expect(editor).toHaveValue(body);
  await editor.fill('GitHub 2FA\ntotp: INVALID!');
  await editor.press('Escape');
  await expect(entry.getByRole('status')).toBeVisible();
  await expect(entry.locator('.entry-text')).toContainText('INVALID!');
  await expect(copy).toHaveCount(0);
  await entry.locator('.entry-text').click();
  await editor.fill(`otpauth://totp/GitHub%3Aalice?secret=${secret}`);
  await editor.press('Escape');
  await expect(page.getByRole('button', {name: '复制验证码', exact: true})).toHaveText('复制验证码');
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: '/tmp/text-vault-totp-mobile.png'});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({width: 1280, height: 800});
  await page.screenshot({path: '/tmp/text-vault-totp-desktop.png'});
  await page.locator('.entry-text').filter({hasText: 'otpauth://totp/GitHub'}).click();
  await editor.fill('GitHub 普通备注');
  await editor.press('Escape');
  await expect(page.getByRole('button', {name: '复制验证码', exact: true})).toHaveCount(0);
  await expect(page.getByText('GitHub 普通备注', {exact: true})).toBeVisible();
  expect(errors).toEqual([]);
});
